# Copyright (C) 2019 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "quarterly"

- package-ecosystem: "docker"
  directory: "/.devcontainer"
  schedule:
    interval: "quarterly"

- package-ecosystem: "pip"
  directory: "/build-scripts"
  schedule:
    interval: "quarterly"
