# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Built-in WASM_ENABLE_* / WASM_DISABLE_* -> WAMR_BUILD_* table.

Generated by `python3 cmake_map.py <repo-root>`, then committed so the common
path costs zero IO.  tests/flag_tracer/test_map_drift.py re-parses the cmake
tree and fails if this table drifts; regenerate and paste when it does.

A macro maps to *all* switches that must be on together (a conjunction), e.g.
WASM_ENABLE_FAST_INTERP needs both WAMR_BUILD_INTERP and WAMR_BUILD_FAST_INTERP.
"""

KNOWN = {
    "WASM_DISABLE_HW_BOUND_CHECK": ("WAMR_DISABLE_HW_BOUND_CHECK", ),
    "WASM_DISABLE_STACK_HW_BOUND_CHECK": ("WAMR_DISABLE_HW_BOUND_CHECK", "WAMR_DISABLE_STACK_HW_BOUND_CHECK", ),
    "WASM_DISABLE_WAKEUP_BLOCKING_OP": ("WAMR_DISABLE_WAKEUP_BLOCKING_OP", ),
    "WASM_ENABLE_AOT": ("WAMR_BUILD_AOT", ),
    "WASM_ENABLE_AOT_INTRINSICS": ("WAMR_BUILD_AOT", "WAMR_BUILD_AOT_INTRINSICS", ),
    "WASM_ENABLE_AOT_STACK_FRAME": ("WAMR_BUILD_AOT", "WAMR_BUILD_AOT_STACK_FRAME", "WAMR_BUILD_DUMP_CALL_STACK", "WAMR_BUILD_GC", "WAMR_BUILD_JIT", "WAMR_BUILD_PERF_PROFILING", ),
    "WASM_ENABLE_AOT_VALIDATOR": ("WAMR_BUILD_AOT_VALIDATOR", ),
    "WASM_ENABLE_BRANCH_HINTS": ("WAMR_BUILD_BRANCH_HINTS", ),
    "WASM_ENABLE_BULK_MEMORY": ("WAMR_BUILD_BULK_MEMORY", ),
    "WASM_ENABLE_BULK_MEMORY_OPT": ("WAMR_BUILD_BULK_MEMORY_OPT", ),
    "WASM_ENABLE_CALL_INDIRECT_OVERLONG": ("WAMR_BUILD_CALL_INDIRECT_OVERLONG", ),
    "WASM_ENABLE_COPY_CALL_STACK": ("WAMR_BUILD_COPY_CALL_STACK", ),
    "WASM_ENABLE_CUSTOM_NAME_SECTION": ("WAMR_BUILD_CUSTOM_NAME_SECTION", ),
    "WASM_ENABLE_DEBUG_AOT": ("WAMR_BUILD_AOT", "WAMR_BUILD_DEBUG_AOT", ),
    "WASM_ENABLE_DEBUG_INTERP": ("WAMR_BUILD_DEBUG_INTERP", ),
    "WASM_ENABLE_DUMP_CALL_STACK": ("WAMR_BUILD_DUMP_CALL_STACK", ),
    "WASM_ENABLE_DYNAMIC_AOT_DEBUG": ("WAMR_BUILD_DYNAMIC_AOT_DEBUG", ),
    "WASM_ENABLE_EXCE_HANDLING": ("WAMR_BUILD_EXCE_HANDLING", ),
    "WASM_ENABLE_EXTENDED_CONST_EXPR": ("WAMR_BUILD_EXTENDED_CONST_EXPR", ),
    "WASM_ENABLE_FAST_INTERP": ("WAMR_BUILD_FAST_INTERP", "WAMR_BUILD_INTERP", ),
    "WASM_ENABLE_FAST_JIT": ("WAMR_BUILD_FAST_JIT", ),
    "WASM_ENABLE_FAST_JIT_DUMP": ("WAMR_BUILD_FAST_JIT", "WAMR_BUILD_FAST_JIT_DUMP", ),
    "WASM_ENABLE_GC": ("WAMR_BUILD_GC", ),
    "WASM_ENABLE_GC_PERF_PROFILING": ("WAMR_BUILD_GC", "WAMR_BUILD_GC_PERF_PROFILING", ),
    "WASM_ENABLE_GLOBAL_HEAP_POOL": ("WAMR_BUILD_GLOBAL_HEAP_POOL", ),
    "WASM_ENABLE_HEAP_AUX_STACK_ALLOCATION": ("WAMR_BUILD_LIB_WASI_THREADS", ),
    "WASM_ENABLE_INSTRUCTION_METERING": ("WAMR_BUILD_INSTRUCTION_METERING", ),
    "WASM_ENABLE_INTERP": ("WAMR_BUILD_INTERP", ),
    "WASM_ENABLE_JIT": ("WAMR_BUILD_JIT", ),
    "WASM_ENABLE_LAZY_JIT": ("WAMR_BUILD_FAST_JIT", "WAMR_BUILD_JIT", "WAMR_BUILD_LAZY_JIT", ),
    "WASM_ENABLE_LIBC_BUILTIN": ("WAMR_BUILD_LIBC_BUILTIN", ),
    "WASM_ENABLE_LIBC_EMCC": ("WAMR_BUILD_LIBC_EMCC", ),
    "WASM_ENABLE_LIBC_WASI": ("WAMR_BUILD_LIBC_UVWASI", "WAMR_BUILD_LIBC_WASI", ),
    "WASM_ENABLE_LIB_PTHREAD": ("WAMR_BUILD_LIB_PTHREAD", ),
    "WASM_ENABLE_LIB_PTHREAD_SEMAPHORE": ("WAMR_BUILD_LIB_PTHREAD", "WAMR_BUILD_LIB_PTHREAD_SEMAPHORE", ),
    "WASM_ENABLE_LIB_RATS": ("WAMR_BUILD_LIB_RATS", ),
    "WASM_ENABLE_LIB_WASI_THREADS": ("WAMR_BUILD_LIB_WASI_THREADS", ),
    "WASM_ENABLE_LINUX_PERF": ("WAMR_BUILD_LINUX_PERF", ),
    "WASM_ENABLE_LOAD_CUSTOM_SECTION": ("WAMR_BUILD_LOAD_CUSTOM_SECTION", ),
    "WASM_ENABLE_MEMORY64": ("WAMR_BUILD_MEMORY64", ),
    "WASM_ENABLE_MEMORY_PROFILING": ("WAMR_BUILD_MEMORY_PROFILING", ),
    "WASM_ENABLE_MEMORY_TRACING": ("WAMR_BUILD_MEMORY_TRACING", ),
    "WASM_ENABLE_MINI_LOADER": ("WAMR_BUILD_MINI_LOADER", ),
    "WASM_ENABLE_MODULE_INST_CONTEXT": ("WAMR_BUILD_MODULE_INST_CONTEXT", ),
    "WASM_ENABLE_MULTI_MEMORY": ("WAMR_BUILD_MULTI_MEMORY", ),
    "WASM_ENABLE_MULTI_MODULE": ("WAMR_BUILD_MULTI_MODULE", ),
    "WASM_ENABLE_PERF_PROFILING": ("WAMR_BUILD_PERF_PROFILING", ),
    "WASM_ENABLE_QUICK_AOT_ENTRY": ("WAMR_BUILD_AOT", "WAMR_BUILD_JIT", "WAMR_BUILD_QUICK_AOT_ENTRY", ),
    "WASM_ENABLE_REF_TYPES": ("WAMR_BUILD_REF_TYPES", ),
    "WASM_ENABLE_SGX_IPFS": ("WAMR_BUILD_SGX_IPFS", ),
    "WASM_ENABLE_SHARED_HEAP": ("WAMR_BUILD_SHARED_HEAP", ),
    "WASM_ENABLE_SHARED_MEMORY": ("WAMR_BUILD_SHARED_MEMORY", ),
    "WASM_ENABLE_SHRUNK_MEMORY": ("WAMR_BUILD_SHRUNK_MEMORY", ),
    "WASM_ENABLE_SIMD": ("WAMR_BUILD_SIMD", ),
    "WASM_ENABLE_SIMDE": ("WAMR_BUILD_FAST_INTERP", "WAMR_BUILD_SIMD", ),
    "WASM_ENABLE_SPEC_TEST": ("WAMR_BUILD_SPEC_TEST", ),
    "WASM_ENABLE_STATIC_PGO": ("WAMR_BUILD_STATIC_PGO", ),
    "WASM_ENABLE_STRINGREF": ("WAMR_BUILD_GC", "WAMR_BUILD_STRINGREF", ),
    "WASM_ENABLE_TAGS": ("WAMR_BUILD_EXCE_HANDLING", ),
    "WASM_ENABLE_TAIL_CALL": ("WAMR_BUILD_TAIL_CALL", ),
    "WASM_ENABLE_THREAD_MGR": ("WAMR_BUILD_THREAD_MGR", ),
    "WASM_ENABLE_UVWASI": ("WAMR_BUILD_LIBC_UVWASI", ),
    "WASM_ENABLE_WASI_EPHEMERAL_NN": ("WAMR_BUILD_WASI_EPHEMERAL_NN", "WAMR_BUILD_WASI_NN", ),
    "WASM_ENABLE_WASI_NN": ("WAMR_BUILD_WASI_NN", ),
    "WASM_ENABLE_WASI_NN_EXTERNAL_DELEGATE": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_ENABLE_EXTERNAL_DELEGATE", ),
    "WASM_ENABLE_WASI_NN_GPU": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_ENABLE_GPU", ),
    "WASM_ENABLE_WASI_NN_LLAMACPP": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_LLAMACPP", ),
    "WASM_ENABLE_WASI_NN_ONNX": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_ONNX", ),
    "WASM_ENABLE_WASI_NN_OPENVINO": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_OPENVINO", ),
    "WASM_ENABLE_WASI_NN_TFLITE": ("WAMR_BUILD_WASI_NN", "WAMR_BUILD_WASI_NN_TFLITE", ),
    "WASM_ENABLE_WASI_TEST": ("WAMR_BUILD_WASI_TEST", ),
    "WASM_ENABLE_WASM_CACHE": ("WAMR_BUILD_WASM_CACHE", ),
}

KNOWN_DIRS = {
    "build-scripts": ("WAMR_BUILD_WASM_CACHE", ),
    "core/iwasm/aot": ("WAMR_BUILD_AOT", ),
    "core/iwasm/common/gc": ("WAMR_BUILD_GC", ),
    "core/iwasm/compilation": ("WAMR_BUILD_JIT", ),
    "core/iwasm/fast-jit": ("WAMR_BUILD_FAST_JIT", ),
    "core/iwasm/interpreter": ("WAMR_BUILD_INTERP", ),
    "core/iwasm/libraries/debug-engine": ("WAMR_BUILD_DEBUG_INTERP", ),
    "core/iwasm/libraries/lib-pthread": ("WAMR_BUILD_LIB_PTHREAD", ),
    "core/iwasm/libraries/lib-rats": ("WAMR_BUILD_LIB_RATS", ),
    "core/iwasm/libraries/lib-wasi-threads": ("WAMR_BUILD_LIB_WASI_THREADS", ),
    "core/iwasm/libraries/libc-builtin": ("WAMR_BUILD_LIBC_BUILTIN", ),
    "core/iwasm/libraries/libc-emcc": ("WAMR_BUILD_LIBC_EMCC", ),
    "core/iwasm/libraries/libc-uvwasi": ("WAMR_BUILD_LIBC_UVWASI", ),
    "core/iwasm/libraries/libc-wasi": ("WAMR_BUILD_LIBC_WASI", ),
    "core/iwasm/libraries/shared-heap": ("WAMR_BUILD_SHARED_HEAP", ),
    "core/iwasm/libraries/simde": ("WAMR_BUILD_FAST_INTERP", "WAMR_BUILD_SIMD", ),
    "core/iwasm/libraries/thread-mgr": ("WAMR_BUILD_THREAD_MGR", ),
    "core/iwasm/libraries/wasi-nn": ("WAMR_BUILD_WASI_NN", ),
    "core/iwasm/libraries/wasi-nn/cmake": ("WAMR_BUILD_WASI_NN", ),
}

KNOWN_FILES = {
    "core/iwasm/aot/arch/aot_reloc_aarch64.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_arc.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_arm.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_dummy.c": ("WAMR_BUILD_AOT", "WAMR_BUILD_WAMR_COMPILER", ),
    "core/iwasm/aot/arch/aot_reloc_mips.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_riscv.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_thumb.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_x86_32.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_x86_64.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/aot/arch/aot_reloc_xtensa.c": ("WAMR_BUILD_AOT", ),
    "core/iwasm/common/gc/stringref/stringref_stub.c": ("WAMR_BUILD_GC", "WAMR_BUILD_STRINGREF", ),
    "core/iwasm/interpreter/wasm_interp_classic.c": ("WAMR_BUILD_INTERP", ),
    "core/iwasm/interpreter/wasm_interp_fast.c": ("WAMR_BUILD_FAST_INTERP", "WAMR_BUILD_INTERP", ),
    "core/iwasm/interpreter/wasm_loader.c": ("WAMR_BUILD_INTERP", ),
    "core/iwasm/interpreter/wasm_mini_loader.c": ("WAMR_BUILD_INTERP", "WAMR_BUILD_MINI_LOADER", ),
    "core/iwasm/libraries/lib-wasi-threads/lib_wasi_threads_wrapper.c": ("WAMR_BUILD_LIB_WASI_THREADS", ),
    "core/iwasm/libraries/wasi-nn/src/wasi_nn.c": ("WAMR_BUILD_WASI_NN", ),
}
# WASM_DISABLE_* macros are inverted: the switch turns the feature *off*.
DISABLE_POLARITY = tuple(m for m in KNOWN if m.startswith("WASM_DISABLE_"))

# Build targets a change can land in, and the cmake project that builds each.
# Everything under core/ reaches iwasm; the AOT compiler front end is built
# only by wamrc (and, inside iwasm, only when WAMR_BUILD_JIT is on).
TARGETS = {
    "iwasm": "product-mini/platforms/linux",
    "wamrc": "wamr-compiler",
}
WAMRC_DIRS = (
    "core/iwasm/compilation",
    "wamr-compiler",
)
WAMRC_ONLY_DIRS = (
    "wamr-compiler",
)
