/*
 * Copyright (C) 2026 Airbus Defence and Space Romania SRL. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#ifndef WASM_COMPONENT_HOST_RESOURCE_H
#define WASM_COMPONENT_HOST_RESOURCE_H

#include <stdint.h>
#include <stdbool.h>
#include "bh_hashmap.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum HostResourceType {
    WASI_P2_ERROR = 1,                         // error
    WASI_P2_IO_INPUT_STREAM = 2,               // input-stream
    WASI_P2_IO_OUTPUT_STREAM = 3,              // output-stream
    WASI_P2_DIRECTORY_ENTRY_STREAM = 4,        // directory-entry-stream
    WASI_P2_FILESYSTEM_DESCRIPTOR = 5,         // descriptor
    WASI_P2_TERMINAL_OUTPUT = 6,               // terminal-output
    WASI_P2_TERMINAL_INPUT = 7,                // terminal-input
    WASI_P2_TCP_SOCKET = 8,                    // tcp-socket
    WASI_P2_UDP_SOCKET = 9,                    // udp-socket
    WASI_P2_NETWORK = 10,                      // network
    WASI_P2_UDP_INCOMING_DATAGRAM_STREAM = 11, // incoming-stream
    WASI_P2_UDP_OUTGOING_DATAGRAM_STREAM = 12, // outgoing-stream
    WASI_P2_POLLABLE = 13,                     // pollable
    WASI_P2_RESOLVE_ADDRESS_STREAM = 14,       // resolve-address-stream
} HostResourceType;

typedef enum IOStreamType {
    STREAM_TYPE_SOCKET = 1, // generated by sockets:tcp
    STREAM_TYPE_FILE = 2,   // generated by filesystem:desriptor
    STREAM_TYPE_GENERIC = 3 // generated by cli:stdout / cli:stdin / cli:stderr
} IOStreamType;

typedef struct StreamResourceType {
    IOStreamType type;
    uint32_t fd;
} StreamResourceType;

typedef void (*host_resource_dtor_t)(void *data);

typedef struct HostResource {
    void *data;
    HostResourceType type;
    host_resource_dtor_t dtor;
} HostResource;

typedef HashMap HostResourceTable;

extern HostResourceTable *g_host_resource_table;

bool
instantiate_host_resource_table();
HostResourceTable *
get_global_host_resource_table();
void
destroy_host_resource_table();

uint32_t
host_resource_table_add(HostResourceTable *table, HostResource *hr);
HostResource *
host_resource_table_get(HostResourceTable *table, uint32_t id);
uint32_t
host_resource_table_delete(HostResourceTable *table, uint32_t id);
uint32_t
host_resource_table_get_next_id(HostResourceType type);

// Helpers
HostResource *
host_resource_create(HostResourceType type, uint32_t data_size);

void
host_resource_set_dtor(HostResource *hr, host_resource_dtor_t dtor);

void
destroy_host_resource(HostResource *hr);

#ifdef __cplusplus
}
#endif

#endif
